name: spotify_ui
description: "A new Flutter project."

publish_to: 'none' 



environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  socket_io_client: ^2.0.3+1 
  http_parser: ^4.0.2
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.9
  camera: ^0.11.1
  image: ^4.0.0
  dio: ^5.8.0+1
  isolate: ^2.1.1
  path_provider: ^2.1.2
  flutter_isolate: ^2.1.0
  palette_generator: ^0.3.3


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  video_compress: ^3.1.4

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/logo/
    - assets/svg/
    - lib/.env


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins_Bold.ttf
        - asset: assets/fonts/Poppins_Medium.ttf
        - asset: assets/fonts/Poppins_SemiBold.ttf


